###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-rschsrv.ece.gatech.edu)
#  Generated on:      Sat Feb 14 12:56:50 2026
#  Design:            counter_16bit
#  Command:           write_design -tempus dbs/postroute
###############################################################

#dataVar is dir where this script is found
set dataVar [file dirname [file normalize [info script]]]

#initialize the design
source $dataVar/counter_16bit.tempus_init.tcl

read_metric -id current $dataVar/counter_16bit.metrics.json.gz

