###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-linlabsrv01)
#  Generated on:      Mon Mar 23 22:44:00 2026
#  Design:            Core
#  Command:           write_design -tempus dbs/postroute
###############################################################

#dataVar is dir where this script is found
set dataVar [file dirname [file normalize [info script]]]

#initialize the design
source $dataVar/Core.tempus_init.tcl

read_metric -id current $dataVar/Core.metrics.json.gz

