###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-rschsrv.ece.gatech.edu)
#  Generated on:      Mon Mar 16 12:29:00 2026
#  Design:            Core
#  Command:           check_design -out_file reports/floorplan/check.design.tcl -type {timing place opt}
###############################################################
#Design Check : timing (20)
# --------------------------------------------------------------------------------------
# Message: Clock pin %s of instance %s has no clock constraint for view name %s.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks timing CHKTIM-4 {
  severity warning
  count 20
  violations {
    {G InstructionDecode_Module_J_IMM_reg[20] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[1] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[2] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[3] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[4] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[5] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[6] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[7] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[8] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[9] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[10] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[11] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[12] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[13] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[14] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[15] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[16] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[17] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[18] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[19] tt_v1.8_25C_Nominal_25_func}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: Macro cell <%s> should have a fully covered obstruction.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-11 {
  severity error
  count 1
  violations {
    {sky130_sram_2kbyte_1rw1r_32x512_8}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: %d unplaced pins detected, please place them properly or add "set_db place_global_place_io_pins true" to place them automatically in the flow.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-51 {
  severity warning
  count 1
  violations {
    {3}
  }
}
#Design Check : place (2)
# --------------------------------------------------------------------------------------
# Message: Instance %s of macro cell %s is not fixed. Please update the place_status to fixed prior to running placement.
#    Help: {Instance of macro cell should be fixed status before running placement.}
# --------------------------------------------------------------------------------------
dict set design_checks place IMPFP-7016 {
  severity error
  count 2
  violations {
    {InstructionFetch_Module_InstructionMemory_instr_sram sky130_sram_2kbyte_1rw1r_32x512_8}
    {MainMemory_data_sram sky130_sram_2kbyte_1rw1r_32x512_8}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Design is not placed. Place the design before running
#    Help: Use place_design or place_opt_design to place the design.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2901 {
  severity warning
  count 1
  violations {
    {}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Maximum transition %.3f is too small compared to maximum transition threshold %.3f, this would result in excessive buffering.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2908 {
  severity warning
  count 1
  violations {
    {0.040 0.599}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: %d instance(s) out of %d are unplaced.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-7276 {
  severity warning
  count 1
  violations {
    {7016 7016}
  }
}
