###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-linlabsrv01)
#  Generated on:      Mon Mar 23 22:22:56 2026
#  Design:            Core
#  Command:           check_design -out_file reports/prects/check.design.tcl -type {timing place opt}
###############################################################
#Design Check : timing (20)
# --------------------------------------------------------------------------------------
# Message: Clock pin %s of instance %s has no clock constraint for view name %s.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks timing CHKTIM-4 {
  severity warning
  count 20
  violations {
    {G InstructionDecode_Module_J_IMM_reg[1] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[2] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[3] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[4] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[5] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[6] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[7] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[8] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[9] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[10] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[11] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[12] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[13] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[14] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[15] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[16] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[17] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[18] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[19] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[20] tt_v1.8_25C_Nominal_25_func}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: Macro cell <%s> should have a fully covered obstruction.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-11 {
  severity error
  count 1
  violations {
    {sky130_sram_2kbyte_1rw1r_32x512_8}
  }
}
#Design Check : place (2)
# --------------------------------------------------------------------------------------
# Message: %s has been chosen to fit to %s but it's %s NOT fit to grid.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place IMPFP-10119 {
  severity error
  count 2
  violations {
    {InstructionFetch_Module_InstructionMemory_instr_sram InstanceGrid height}
    {MainMemory_data_sram InstanceGrid height}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: Instance %s not snapped to row-site.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place IMPFP-10122 {
  severity info
  count 1
  violations {
    {g35259}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Maximum transition %.3f is too small compared to maximum transition threshold %.3f, this would result in excessive buffering.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2908 {
  severity warning
  count 1
  violations {
    {0.040 0.599}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Running power optimization flow with leakage to dynamic ratio of %f but without activity file loaded.
#    Help: Please provide activity file.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-7264 {
  severity warning
  count 1
  violations {
    {0.500000}
  }
}
