###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-rschsrv.ece.gatech.edu)
#  Generated on:      Sat Feb 14 12:41:22 2026
#  Design:            counter_16bit
#  Command:           check_design -out_file reports/floorplan/check.design.tcl -type {timing place opt}
###############################################################
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Design is not placed. Place the design before running
#    Help: Use place_design or place_opt_design to place the design.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2901 {
  severity warning
  count 1
  violations {
    {}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Maximum transition %.3f is too small compared to maximum transition threshold %.3f, this would result in excessive buffering.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2908 {
  severity warning
  count 1
  violations {
    {0.150 0.599}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: %d instance(s) out of %d are unplaced.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-7276 {
  severity warning
  count 1
  violations {
    {139 139}
  }
}
