###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-rschsrv.ece.gatech.edu)
#  Generated on:      Mon Mar 16 12:44:18 2026
#  Design:            Core
#  Command:           check_design -out_file reports/postcts/check.design.tcl -type {timing place opt cts}
###############################################################
#Design Check : timing (20)
# --------------------------------------------------------------------------------------
# Message: Clock pin %s of instance %s has no clock constraint for view name %s.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks timing CHKTIM-4 {
  severity warning
  count 20
  violations {
    {G InstructionDecode_Module_J_IMM_reg[20] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[1] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[2] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[3] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[4] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[5] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[6] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[7] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[8] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[9] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[10] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[11] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[12] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[13] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[14] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[15] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[16] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[17] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[18] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[19] tt_v1.8_25C_Nominal_25_func}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: Macro cell <%s> should have a fully covered obstruction.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-11 {
  severity error
  count 1
  violations {
    {sky130_sram_2kbyte_1rw1r_32x512_8}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: %d unplaced pins detected, please place them properly or add "set_db place_global_place_io_pins true" to place them automatically in the flow.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-51 {
  severity warning
  count 1
  violations {
    {3}
  }
}
#Design Check : place (2)
# --------------------------------------------------------------------------------------
# Message: %s has been chosen to fit to %s but it's %s NOT fit to grid.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place IMPFP-10119 {
  severity error
  count 2
  violations {
    {InstructionFetch_Module_InstructionMemory_instr_sram InstanceGrid height}
    {MainMemory_data_sram InstanceGrid height}
  }
}
#Design Check : place (202)
# --------------------------------------------------------------------------------------
# Message: Follow pin (Pin Box:%s) routed over hard macro (%s) should be cut at macro boundary.
#    Help: {Follow pin cannot be routed over hard macros. So it should be cut at macro boundary.}
# --------------------------------------------------------------------------------------
dict set design_checks place IMPFP-7006 {
  severity error
  count 202
  violations {
    {{(29.9000000000 , 750.0600000000) (995.9000000000 , 750.4600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 758.3400000000) (995.9000000000 , 758.7400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 766.6200000000) (995.9000000000 , 767.0200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 774.9000000000) (995.9000000000 , 775.3000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 783.1800000000) (995.9000000000 , 783.5800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 791.4600000000) (995.9000000000 , 791.8600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 799.7400000000) (995.9000000000 , 800.1400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 808.0200000000) (995.9000000000 , 808.4200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 816.3000000000) (995.9000000000 , 816.7000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 824.5800000000) (995.9000000000 , 824.9800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 832.8600000000) (995.9000000000 , 833.2600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 841.1400000000) (995.9000000000 , 841.5400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 849.4200000000) (995.9000000000 , 849.8200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 857.7000000000) (995.9000000000 , 858.1000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 865.9800000000) (995.9000000000 , 866.3800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 874.2600000000) (995.9000000000 , 874.6600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 882.5400000000) (995.9000000000 , 882.9400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 890.8200000000) (995.9000000000 , 891.2200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 899.1000000000) (995.9000000000 , 899.5000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 907.3800000000) (995.9000000000 , 907.7800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 915.6600000000) (995.9000000000 , 916.0600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 923.9400000000) (995.9000000000 , 924.3400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 932.2200000000) (995.9000000000 , 932.6200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 940.5000000000) (995.9000000000 , 940.9000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 948.7800000000) (995.9000000000 , 949.1800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 957.0600000000) (995.9000000000 , 957.4600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 965.3400000000) (995.9000000000 , 965.7400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 973.6200000000) (995.9000000000 , 974.0200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 981.9000000000) (995.9000000000 , 982.3000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 990.1800000000) (995.9000000000 , 990.5800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 998.4600000000) (995.9000000000 , 998.8600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1006.7400000000) (995.9000000000 , 1007.1400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1015.0200000000) (995.9000000000 , 1015.4200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1023.3000000000) (995.9000000000 , 1023.7000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1031.5800000000) (995.9000000000 , 1031.9800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1039.8600000000) (995.9000000000 , 1040.2600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1048.1400000000) (995.9000000000 , 1048.5400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1056.4200000000) (995.9000000000 , 1056.8200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1064.7000000000) (995.9000000000 , 1065.1000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1072.9800000000) (995.9000000000 , 1073.3800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1081.2600000000) (995.9000000000 , 1081.6600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1089.5400000000) (995.9000000000 , 1089.9400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1097.8200000000) (995.9000000000 , 1098.2200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1106.1000000000) (995.9000000000 , 1106.5000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1114.3800000000) (995.9000000000 , 1114.7800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1122.6600000000) (995.9000000000 , 1123.0600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1130.9400000000) (995.9000000000 , 1131.3400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1139.2200000000) (995.9000000000 , 1139.6200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1147.5000000000) (995.9000000000 , 1147.9000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1155.7800000000) (995.9000000000 , 1156.1800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1164.0600000000) (995.9000000000 , 1164.4600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 754.2000000000) (995.9000000000 , 754.6000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 762.4800000000) (995.9000000000 , 762.8800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 770.7600000000) (995.9000000000 , 771.1600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 779.0400000000) (995.9000000000 , 779.4400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 787.3200000000) (995.9000000000 , 787.7200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 795.6000000000) (995.9000000000 , 796.0000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 803.8800000000) (995.9000000000 , 804.2800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 812.1600000000) (995.9000000000 , 812.5600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 820.4400000000) (995.9000000000 , 820.8400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 828.7200000000) (995.9000000000 , 829.1200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 837.0000000000) (995.9000000000 , 837.4000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 845.2800000000) (995.9000000000 , 845.6800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 853.5600000000) (995.9000000000 , 853.9600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 861.8400000000) (995.9000000000 , 862.2400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 870.1200000000) (995.9000000000 , 870.5200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 878.4000000000) (995.9000000000 , 878.8000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 886.6800000000) (995.9000000000 , 887.0800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 894.9600000000) (995.9000000000 , 895.3600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 903.2400000000) (995.9000000000 , 903.6400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 911.5200000000) (995.9000000000 , 911.9200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 919.8000000000) (995.9000000000 , 920.2000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 928.0800000000) (995.9000000000 , 928.4800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 936.3600000000) (995.9000000000 , 936.7600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 944.6400000000) (995.9000000000 , 945.0400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 952.9200000000) (995.9000000000 , 953.3200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 961.2000000000) (995.9000000000 , 961.6000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 969.4800000000) (995.9000000000 , 969.8800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 977.7600000000) (995.9000000000 , 978.1600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 986.0400000000) (995.9000000000 , 986.4400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 994.3200000000) (995.9000000000 , 994.7200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1002.6000000000) (995.9000000000 , 1003.0000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1010.8800000000) (995.9000000000 , 1011.2800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1019.1600000000) (995.9000000000 , 1019.5600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1027.4400000000) (995.9000000000 , 1027.8400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1035.7200000000) (995.9000000000 , 1036.1200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1044.0000000000) (995.9000000000 , 1044.4000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1052.2800000000) (995.9000000000 , 1052.6800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1060.5600000000) (995.9000000000 , 1060.9600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1068.8400000000) (995.9000000000 , 1069.2400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1077.1200000000) (995.9000000000 , 1077.5200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1085.4000000000) (995.9000000000 , 1085.8000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1093.6800000000) (995.9000000000 , 1094.0800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1101.9600000000) (995.9000000000 , 1102.3600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1110.2400000000) (995.9000000000 , 1110.6400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1118.5200000000) (995.9000000000 , 1118.9200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1126.8000000000) (995.9000000000 , 1127.2000000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1135.0800000000) (995.9000000000 , 1135.4800000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1143.3600000000) (995.9000000000 , 1143.7600000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1151.6400000000) (995.9000000000 , 1152.0400000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 1159.9200000000) (995.9000000000 , 1160.3200000000)} InstructionFetch_Module_InstructionMemory_instr_sram}
    {{(29.9000000000 , 137.3400000000) (995.9000000000 , 137.7400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 145.6200000000) (995.9000000000 , 146.0200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 153.9000000000) (995.9000000000 , 154.3000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 162.1800000000) (995.9000000000 , 162.5800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 170.4600000000) (995.9000000000 , 170.8600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 178.7400000000) (995.9000000000 , 179.1400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 187.0200000000) (995.9000000000 , 187.4200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 195.3000000000) (995.9000000000 , 195.7000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 203.5800000000) (995.9000000000 , 203.9800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 211.8600000000) (995.9000000000 , 212.2600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 220.1400000000) (995.9000000000 , 220.5400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 228.4200000000) (995.9000000000 , 228.8200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 236.7000000000) (995.9000000000 , 237.1000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 244.9800000000) (995.9000000000 , 245.3800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 253.2600000000) (995.9000000000 , 253.6600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 261.5400000000) (995.9000000000 , 261.9400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 269.8200000000) (995.9000000000 , 270.2200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 278.1000000000) (995.9000000000 , 278.5000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 286.3800000000) (995.9000000000 , 286.7800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 294.6600000000) (995.9000000000 , 295.0600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 302.9400000000) (995.9000000000 , 303.3400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 311.2200000000) (995.9000000000 , 311.6200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 319.5000000000) (995.9000000000 , 319.9000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 327.7800000000) (995.9000000000 , 328.1800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 336.0600000000) (995.9000000000 , 336.4600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 344.3400000000) (995.9000000000 , 344.7400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 352.6200000000) (995.9000000000 , 353.0200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 360.9000000000) (995.9000000000 , 361.3000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 369.1800000000) (995.9000000000 , 369.5800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 377.4600000000) (995.9000000000 , 377.8600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 385.7400000000) (995.9000000000 , 386.1400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 394.0200000000) (995.9000000000 , 394.4200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 402.3000000000) (995.9000000000 , 402.7000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 410.5800000000) (995.9000000000 , 410.9800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 418.8600000000) (995.9000000000 , 419.2600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 427.1400000000) (995.9000000000 , 427.5400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 435.4200000000) (995.9000000000 , 435.8200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 443.7000000000) (995.9000000000 , 444.1000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 451.9800000000) (995.9000000000 , 452.3800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 460.2600000000) (995.9000000000 , 460.6600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 468.5400000000) (995.9000000000 , 468.9400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 476.8200000000) (995.9000000000 , 477.2200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 485.1000000000) (995.9000000000 , 485.5000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 493.3800000000) (995.9000000000 , 493.7800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 501.6600000000) (995.9000000000 , 502.0600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 509.9400000000) (995.9000000000 , 510.3400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 518.2200000000) (995.9000000000 , 518.6200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 526.5000000000) (995.9000000000 , 526.9000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 534.7800000000) (995.9000000000 , 535.1800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 543.0600000000) (995.9000000000 , 543.4600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 133.2000000000) (995.9000000000 , 133.6000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 141.4800000000) (995.9000000000 , 141.8800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 149.7600000000) (995.9000000000 , 150.1600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 158.0400000000) (995.9000000000 , 158.4400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 166.3200000000) (995.9000000000 , 166.7200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 174.6000000000) (995.9000000000 , 175.0000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 182.8800000000) (995.9000000000 , 183.2800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 191.1600000000) (995.9000000000 , 191.5600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 199.4400000000) (995.9000000000 , 199.8400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 207.7200000000) (995.9000000000 , 208.1200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 216.0000000000) (995.9000000000 , 216.4000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 224.2800000000) (995.9000000000 , 224.6800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 232.5600000000) (995.9000000000 , 232.9600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 240.8400000000) (995.9000000000 , 241.2400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 249.1200000000) (995.9000000000 , 249.5200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 257.4000000000) (995.9000000000 , 257.8000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 265.6800000000) (995.9000000000 , 266.0800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 273.9600000000) (995.9000000000 , 274.3600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 282.2400000000) (995.9000000000 , 282.6400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 290.5200000000) (995.9000000000 , 290.9200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 298.8000000000) (995.9000000000 , 299.2000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 307.0800000000) (995.9000000000 , 307.4800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 315.3600000000) (995.9000000000 , 315.7600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 323.6400000000) (995.9000000000 , 324.0400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 331.9200000000) (995.9000000000 , 332.3200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 340.2000000000) (995.9000000000 , 340.6000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 348.4800000000) (995.9000000000 , 348.8800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 356.7600000000) (995.9000000000 , 357.1600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 365.0400000000) (995.9000000000 , 365.4400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 373.3200000000) (995.9000000000 , 373.7200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 381.6000000000) (995.9000000000 , 382.0000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 389.8800000000) (995.9000000000 , 390.2800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 398.1600000000) (995.9000000000 , 398.5600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 406.4400000000) (995.9000000000 , 406.8400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 414.7200000000) (995.9000000000 , 415.1200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 423.0000000000) (995.9000000000 , 423.4000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 431.2800000000) (995.9000000000 , 431.6800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 439.5600000000) (995.9000000000 , 439.9600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 447.8400000000) (995.9000000000 , 448.2400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 456.1200000000) (995.9000000000 , 456.5200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 464.4000000000) (995.9000000000 , 464.8000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 472.6800000000) (995.9000000000 , 473.0800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 480.9600000000) (995.9000000000 , 481.3600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 489.2400000000) (995.9000000000 , 489.6400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 497.5200000000) (995.9000000000 , 497.9200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 505.8000000000) (995.9000000000 , 506.2000000000)} MainMemory_data_sram}
    {{(29.9000000000 , 514.0800000000) (995.9000000000 , 514.4800000000)} MainMemory_data_sram}
    {{(29.9000000000 , 522.3600000000) (995.9000000000 , 522.7600000000)} MainMemory_data_sram}
    {{(29.9000000000 , 530.6400000000) (995.9000000000 , 531.0400000000)} MainMemory_data_sram}
    {{(29.9000000000 , 538.9200000000) (995.9000000000 , 539.3200000000)} MainMemory_data_sram}
    {{(29.9000000000 , 547.2000000000) (995.9000000000 , 547.6000000000)} MainMemory_data_sram}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Maximum transition %.3f is too small compared to maximum transition threshold %.3f, this would result in excessive buffering.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2908 {
  severity warning
  count 1
  violations {
    {0.040 0.599}
  }
}
#Design Check : opt (3)
# --------------------------------------------------------------------------------------
# Message: %s : Net has unplaced terms or is connected to uplaced instances in design.
#    Help: This warning message is issued during optimization if there are nets connected to any unplaced I/O pins or unplaced instances in the design. The unplaced instances can be reported by running check_place command and unplaced I/O's can be reported by running 'check_pin_assignment  -report_violating_pin' command.Once these issues are fixed the warning message will not be reported.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-665 {
  severity warning
  count 3
  violations {
    {clock}
    {reset}
    {mem_en}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: Route type(s) %s used for trunk or top clock nets do not have a non-default rule (NDR) set.
#    Help: Make sure there is a NDR specifed for each route_type for top and trunk nets. Check the cts_route_type attribute to see which route_types are in use for clock nets. Run 'get_db route_type:<name> .rule.name' to see NDR for a route_type called <name>. Run 'help cts_route_type' for more details on how to specify which route_types CTS should use. Run 'help create_route_type' for more details on how to create route_types.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-10 {
  severity warning
  count 1
  violations {
    {default_route_type_nonleaf}
  }
}
#Design Check : cts (2)
# --------------------------------------------------------------------------------------
# Message: Preferred routing layers for route_type %s do not have similar RC characteristics. Mismatch found on layers: %s.
#    Help: Preferred layer ranges for clock nets should have similar RC characteristics for both horizontal and vertical layers. Check the cts_route_type attribute to see which route_types are in use for clock nets. Run 'help report_unit_parasitics' for details on how to check the layer RC values for the preferred layers specified in the route_type.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-16 {
  severity warning
  count 2
  violations {
    {default_route_type_nonleaf met3(H) R=0.157Ohm/um C=0.297fF/um RC=0.047fs/um^2 and met4(V) R=0.157Ohm/um C=0.264fF/um RC=0.041fs/um^2}
    {default_route_type_leaf met3(H) R=0.157Ohm/um C=0.297fF/um RC=0.047fs/um^2 and met4(V) R=0.157Ohm/um C=0.264fF/um RC=0.041fs/um^2}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: Insufficient number of clock gating cells for clock_tree %s and power_domain %s. Have cells: %s.
#    Help: Provide at least three cells to allow CTS to choose from a range of different clock gate sizes. Run 'help cts_clock_gating_cells' for more details on how to specify which clock gates CTS should use.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-24 {
  severity error
  count 1
  violations {
    {core_clock auto-default {}}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: An auto generated scaled skew target of %s will be used for delay_corner %s and delay_type %s for skew_group %s.
#    Help: When using multi-corner skew targets it is recommended to set explicit numeric targets for each delay_corner you want to balance in. Run 'help cts_target_skew' for more details on how to set skew targets.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-4 {
  severity warning
  count 1
  violations {
    {0.183ns tt_v1.8_25C_Nominal_25 late core_clock/func}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: CTS skew target must be set to a numeric value for the primary corner %s for skew_group %s.
#    Help: Set a skew target using the cts_target_skew attribute for the primary half corner. Run 'help cts_target_skew' for more details on how to set skew targets.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-5 {
  severity warning
  count 1
  violations {
    {tt_v1.8_25C_Nominal_25 core_clock/func}
  }
}
#Design Check : cts (2)
# --------------------------------------------------------------------------------------
# Message: CTS maximum transition target %s is too high (maximum %s) for delay_corner %s and delay_type %s for clock_tree %s and net_type %s.
#    Help: The value has been capped at the maximum. Decrease the value set for the cts_target_max_transition_time attribute to avoid this warning. Run 'help cts_target_max_transition_time' for more details on how to set the maximum transition time.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-60 {
  severity warning
  count 2
  violations {
    {100.000ns 0.599ns tt_v1.8_25C_Nominal_25 late core_clock leaf}
    {100.000ns 0.599ns tt_v1.8_25C_Nominal_25 late core_clock trunk}
  }
}
