###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-linlabsrv01)
#  Generated on:      Wed Mar 18 00:16:20 2026
#  Design:            Core
#  Command:           check_design -out_file reports/route/check.design.tcl -type {timing place opt cts route}
###############################################################
#Design Check : timing (20)
# --------------------------------------------------------------------------------------
# Message: Clock pin %s of instance %s has no clock constraint for view name %s.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks timing CHKTIM-4 {
  severity warning
  count 20
  violations {
    {G InstructionDecode_Module_J_IMM_reg[20] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[1] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[2] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[3] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[4] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[5] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[6] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[7] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[8] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[9] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[10] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[11] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[12] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[13] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[14] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[15] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[16] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[17] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[18] tt_v1.8_25C_Nominal_25_func}
    {G InstructionDecode_Module_J_IMM_reg[19] tt_v1.8_25C_Nominal_25_func}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: Macro cell <%s> should have a fully covered obstruction.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-11 {
  severity error
  count 1
  violations {
    {sky130_sram_2kbyte_1rw1r_32x512_8}
  }
}
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: Design has util %.1f% > 100%, placer cannot proceed. The problem may be caused by density screens (softBlockages and partial blockages) or user-specified cell padding. Please correct this problem first.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-41 {
  severity error
  count 1
  violations {
    {100.1}
  }
}
#Design Check : place (2)
# --------------------------------------------------------------------------------------
# Message: %s has been chosen to fit to %s but it's %s NOT fit to grid.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place IMPFP-10119 {
  severity error
  count 2
  violations {
    {InstructionFetch_Module_InstructionMemory_instr_sram InstanceGrid height}
    {MainMemory_data_sram InstanceGrid height}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Maximum transition %.3f is too small compared to maximum transition threshold %.3f, this would result in excessive buffering.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2908 {
  severity warning
  count 1
  violations {
    {0.040 0.599}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: Route type(s) %s used for trunk or top clock nets do not have a non-default rule (NDR) set.
#    Help: Make sure there is a NDR specifed for each route_type for top and trunk nets. Check the cts_route_type attribute to see which route_types are in use for clock nets. Run 'get_db route_type:<name> .rule.name' to see NDR for a route_type called <name>. Run 'help cts_route_type' for more details on how to specify which route_types CTS should use. Run 'help create_route_type' for more details on how to create route_types.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-10 {
  severity warning
  count 1
  violations {
    {default_route_type_nonleaf}
  }
}
#Design Check : cts (2)
# --------------------------------------------------------------------------------------
# Message: Preferred routing layers for route_type %s do not have similar RC characteristics. Mismatch found on layers: %s.
#    Help: Preferred layer ranges for clock nets should have similar RC characteristics for both horizontal and vertical layers. Check the cts_route_type attribute to see which route_types are in use for clock nets. Run 'help report_unit_parasitics' for details on how to check the layer RC values for the preferred layers specified in the route_type.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-16 {
  severity warning
  count 2
  violations {
    {default_route_type_leaf met3(H) R=0.157Ohm/um C=0.297fF/um RC=0.047fs/um^2 and met4(V) R=0.157Ohm/um C=0.264fF/um RC=0.041fs/um^2}
    {default_route_type_nonleaf met3(H) R=0.157Ohm/um C=0.297fF/um RC=0.047fs/um^2 and met4(V) R=0.157Ohm/um C=0.264fF/um RC=0.041fs/um^2}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: Insufficient number of clock gating cells for clock_tree %s and power_domain %s. Have cells: %s.
#    Help: Provide at least three cells to allow CTS to choose from a range of different clock gate sizes. Run 'help cts_clock_gating_cells' for more details on how to specify which clock gates CTS should use.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-24 {
  severity error
  count 1
  violations {
    {core_clock auto-default {}}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: An auto generated scaled skew target of %s will be used for delay_corner %s and delay_type %s for skew_group %s.
#    Help: When using multi-corner skew targets it is recommended to set explicit numeric targets for each delay_corner you want to balance in. Run 'help cts_target_skew' for more details on how to set skew targets.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-4 {
  severity warning
  count 1
  violations {
    {0.183ns tt_v1.8_25C_Nominal_25 late core_clock/func}
  }
}
#Design Check : cts (1)
# --------------------------------------------------------------------------------------
# Message: CTS skew target must be set to a numeric value for the primary corner %s for skew_group %s.
#    Help: Set a skew target using the cts_target_skew attribute for the primary half corner. Run 'help cts_target_skew' for more details on how to set skew targets.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-5 {
  severity warning
  count 1
  violations {
    {tt_v1.8_25C_Nominal_25 core_clock/func}
  }
}
#Design Check : cts (2)
# --------------------------------------------------------------------------------------
# Message: CTS maximum transition target %s is too high (maximum %s) for delay_corner %s and delay_type %s for clock_tree %s and net_type %s.
#    Help: The value has been capped at the maximum. Decrease the value set for the cts_target_max_transition_time attribute to avoid this warning. Run 'help cts_target_max_transition_time' for more details on how to set the maximum transition time.
# --------------------------------------------------------------------------------------
dict set design_checks cts CHKCTS-60 {
  severity warning
  count 2
  violations {
    {100.000ns 0.599ns tt_v1.8_25C_Nominal_25 late core_clock leaf}
    {100.000ns 0.599ns tt_v1.8_25C_Nominal_25 late core_clock trunk}
  }
}
