###############################################################
#  Generated by:      Cadence Innovus 25.11-s102_1
#  OS:                Linux x86_64(Host ID ece-rschsrv.ece.gatech.edu)
#  Generated on:      Fri Mar 13 11:40:10 2026
#  Design:            Core
#  Command:           check_design -out_file reports/prects/check.design.tcl -type {timing place opt}
###############################################################
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: %d unplaced pins detected, please place them properly or add "set_db place_global_place_io_pins true" to place them automatically in the flow.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-51 {
  severity warning
  count 1
  violations {
    {3}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: No constrained timing paths found. Design may not be constrained or library is missing timing information.
#    Help: Please check that the constraint mode definition.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-7286 {
  severity error
  count 1
  violations {
    {}
  }
}
