
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point read_start_addr[8] read_start_addr[8] -type PI PI
add mapped point read_start_addr[7] read_start_addr[7] -type PI PI
add mapped point read_start_addr[6] read_start_addr[6] -type PI PI
add mapped point read_start_addr[5] read_start_addr[5] -type PI PI
add mapped point read_start_addr[4] read_start_addr[4] -type PI PI
add mapped point read_start_addr[3] read_start_addr[3] -type PI PI
add mapped point read_start_addr[2] read_start_addr[2] -type PI PI
add mapped point read_start_addr[1] read_start_addr[1] -type PI PI
add mapped point read_start_addr[0] read_start_addr[0] -type PI PI
add mapped point read_end_addr[8] read_end_addr[8] -type PI PI
add mapped point read_end_addr[7] read_end_addr[7] -type PI PI
add mapped point read_end_addr[6] read_end_addr[6] -type PI PI
add mapped point read_end_addr[5] read_end_addr[5] -type PI PI
add mapped point read_end_addr[4] read_end_addr[4] -type PI PI
add mapped point read_end_addr[3] read_end_addr[3] -type PI PI
add mapped point read_end_addr[2] read_end_addr[2] -type PI PI
add mapped point read_end_addr[1] read_end_addr[1] -type PI PI
add mapped point read_end_addr[0] read_end_addr[0] -type PI PI
add mapped point write_start_addr[8] write_start_addr[8] -type PI PI
add mapped point write_start_addr[7] write_start_addr[7] -type PI PI
add mapped point write_start_addr[6] write_start_addr[6] -type PI PI
add mapped point write_start_addr[5] write_start_addr[5] -type PI PI
add mapped point write_start_addr[4] write_start_addr[4] -type PI PI
add mapped point write_start_addr[3] write_start_addr[3] -type PI PI
add mapped point write_start_addr[2] write_start_addr[2] -type PI PI
add mapped point write_start_addr[1] write_start_addr[1] -type PI PI
add mapped point write_start_addr[0] write_start_addr[0] -type PI PI
add mapped point write_end_addr[8] write_end_addr[8] -type PI PI
add mapped point write_end_addr[7] write_end_addr[7] -type PI PI
add mapped point write_end_addr[6] write_end_addr[6] -type PI PI
add mapped point write_end_addr[5] write_end_addr[5] -type PI PI
add mapped point write_end_addr[4] write_end_addr[4] -type PI PI
add mapped point write_end_addr[3] write_end_addr[3] -type PI PI
add mapped point write_end_addr[2] write_end_addr[2] -type PI PI
add mapped point write_end_addr[1] write_end_addr[1] -type PI PI
add mapped point write_end_addr[0] write_end_addr[0] -type PI PI

//output ports

//inout ports




//Sequential Pins
add mapped point u_ctrl/buffer_control/q u_ctrl_buffer_control_reg/Q -type DLAT DLAT
add mapped point u_ctrl/next[0]/q u_ctrl_next_reg[0]/Q -type DLAT DLAT
add mapped point u_ctrl/next[1]/q u_ctrl_next_reg[1]/Q -type DLAT DLAT
add mapped point u_ctrl/next[2]/q u_ctrl_next_reg[2]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[0]/q u_ctrl_op_a_reg[0]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[1]/q u_ctrl_op_a_reg[1]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[2]/q u_ctrl_op_a_reg[2]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[3]/q u_ctrl_op_a_reg[3]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[4]/q u_ctrl_op_a_reg[4]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[5]/q u_ctrl_op_a_reg[5]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[6]/q u_ctrl_op_a_reg[6]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[7]/q u_ctrl_op_a_reg[7]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[8]/q u_ctrl_op_a_reg[8]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[9]/q u_ctrl_op_a_reg[9]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[10]/q u_ctrl_op_a_reg[10]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[11]/q u_ctrl_op_a_reg[11]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[12]/q u_ctrl_op_a_reg[12]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[13]/q u_ctrl_op_a_reg[13]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[14]/q u_ctrl_op_a_reg[14]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[15]/q u_ctrl_op_a_reg[15]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[16]/q u_ctrl_op_a_reg[16]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[17]/q u_ctrl_op_a_reg[17]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[18]/q u_ctrl_op_a_reg[18]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[19]/q u_ctrl_op_a_reg[19]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[20]/q u_ctrl_op_a_reg[20]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[21]/q u_ctrl_op_a_reg[21]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[22]/q u_ctrl_op_a_reg[22]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[23]/q u_ctrl_op_a_reg[23]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[24]/q u_ctrl_op_a_reg[24]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[25]/q u_ctrl_op_a_reg[25]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[26]/q u_ctrl_op_a_reg[26]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[27]/q u_ctrl_op_a_reg[27]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[28]/q u_ctrl_op_a_reg[28]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[29]/q u_ctrl_op_a_reg[29]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[30]/q u_ctrl_op_a_reg[30]/Q -type DLAT DLAT
add mapped point u_ctrl/op_a[31]/q u_ctrl_op_a_reg[31]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[0]/q u_ctrl_op_b_reg[0]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[1]/q u_ctrl_op_b_reg[1]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[2]/q u_ctrl_op_b_reg[2]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[3]/q u_ctrl_op_b_reg[3]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[4]/q u_ctrl_op_b_reg[4]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[5]/q u_ctrl_op_b_reg[5]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[6]/q u_ctrl_op_b_reg[6]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[7]/q u_ctrl_op_b_reg[7]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[8]/q u_ctrl_op_b_reg[8]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[9]/q u_ctrl_op_b_reg[9]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[10]/q u_ctrl_op_b_reg[10]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[11]/q u_ctrl_op_b_reg[11]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[12]/q u_ctrl_op_b_reg[12]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[13]/q u_ctrl_op_b_reg[13]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[14]/q u_ctrl_op_b_reg[14]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[15]/q u_ctrl_op_b_reg[15]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[16]/q u_ctrl_op_b_reg[16]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[17]/q u_ctrl_op_b_reg[17]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[18]/q u_ctrl_op_b_reg[18]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[19]/q u_ctrl_op_b_reg[19]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[20]/q u_ctrl_op_b_reg[20]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[21]/q u_ctrl_op_b_reg[21]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[22]/q u_ctrl_op_b_reg[22]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[23]/q u_ctrl_op_b_reg[23]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[24]/q u_ctrl_op_b_reg[24]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[25]/q u_ctrl_op_b_reg[25]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[26]/q u_ctrl_op_b_reg[26]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[27]/q u_ctrl_op_b_reg[27]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[28]/q u_ctrl_op_b_reg[28]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[29]/q u_ctrl_op_b_reg[29]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[30]/q u_ctrl_op_b_reg[30]/Q -type DLAT DLAT
add mapped point u_ctrl/op_b[31]/q u_ctrl_op_b_reg[31]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[0]/q u_ctrl_r_addr_reg[0]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[1]/q u_ctrl_r_addr_reg[1]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[2]/q u_ctrl_r_addr_reg[2]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[3]/q u_ctrl_r_addr_reg[3]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[4]/q u_ctrl_r_addr_reg[4]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[5]/q u_ctrl_r_addr_reg[5]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[6]/q u_ctrl_r_addr_reg[6]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[7]/q u_ctrl_r_addr_reg[7]/Q -type DLAT DLAT
add mapped point u_ctrl/r_addr[8]/q u_ctrl_r_addr_reg[8]/Q -type DLAT DLAT
add mapped point u_ctrl/read/q u_ctrl_read_reg/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[0]/q u_ctrl_w_addr_reg[0]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[1]/q u_ctrl_w_addr_reg[1]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[2]/q u_ctrl_w_addr_reg[2]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[3]/q u_ctrl_w_addr_reg[3]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[4]/q u_ctrl_w_addr_reg[4]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[5]/q u_ctrl_w_addr_reg[5]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[6]/q u_ctrl_w_addr_reg[6]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[7]/q u_ctrl_w_addr_reg[7]/Q -type DLAT DLAT
add mapped point u_ctrl/w_addr[8]/q u_ctrl_w_addr_reg[8]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[0]/q u_ctrl_w_data_reg[0]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[1]/q u_ctrl_w_data_reg[1]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[2]/q u_ctrl_w_data_reg[2]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[3]/q u_ctrl_w_data_reg[3]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[4]/q u_ctrl_w_data_reg[4]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[5]/q u_ctrl_w_data_reg[5]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[6]/q u_ctrl_w_data_reg[6]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[7]/q u_ctrl_w_data_reg[7]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[8]/q u_ctrl_w_data_reg[8]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[9]/q u_ctrl_w_data_reg[9]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[10]/q u_ctrl_w_data_reg[10]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[11]/q u_ctrl_w_data_reg[11]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[12]/q u_ctrl_w_data_reg[12]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[13]/q u_ctrl_w_data_reg[13]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[14]/q u_ctrl_w_data_reg[14]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[15]/q u_ctrl_w_data_reg[15]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[16]/q u_ctrl_w_data_reg[16]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[17]/q u_ctrl_w_data_reg[17]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[18]/q u_ctrl_w_data_reg[18]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[19]/q u_ctrl_w_data_reg[19]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[20]/q u_ctrl_w_data_reg[20]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[21]/q u_ctrl_w_data_reg[21]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[22]/q u_ctrl_w_data_reg[22]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[23]/q u_ctrl_w_data_reg[23]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[24]/q u_ctrl_w_data_reg[24]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[25]/q u_ctrl_w_data_reg[25]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[26]/q u_ctrl_w_data_reg[26]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[27]/q u_ctrl_w_data_reg[27]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[28]/q u_ctrl_w_data_reg[28]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[29]/q u_ctrl_w_data_reg[29]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[30]/q u_ctrl_w_data_reg[30]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[31]/q u_ctrl_w_data_reg[31]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[32]/q u_ctrl_w_data_reg[32]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[33]/q u_ctrl_w_data_reg[33]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[34]/q u_ctrl_w_data_reg[34]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[35]/q u_ctrl_w_data_reg[35]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[36]/q u_ctrl_w_data_reg[36]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[37]/q u_ctrl_w_data_reg[37]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[38]/q u_ctrl_w_data_reg[38]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[39]/q u_ctrl_w_data_reg[39]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[40]/q u_ctrl_w_data_reg[40]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[41]/q u_ctrl_w_data_reg[41]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[42]/q u_ctrl_w_data_reg[42]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[43]/q u_ctrl_w_data_reg[43]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[44]/q u_ctrl_w_data_reg[44]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[45]/q u_ctrl_w_data_reg[45]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[46]/q u_ctrl_w_data_reg[46]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[47]/q u_ctrl_w_data_reg[47]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[48]/q u_ctrl_w_data_reg[48]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[49]/q u_ctrl_w_data_reg[49]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[50]/q u_ctrl_w_data_reg[50]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[51]/q u_ctrl_w_data_reg[51]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[52]/q u_ctrl_w_data_reg[52]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[53]/q u_ctrl_w_data_reg[53]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[54]/q u_ctrl_w_data_reg[54]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[55]/q u_ctrl_w_data_reg[55]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[56]/q u_ctrl_w_data_reg[56]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[57]/q u_ctrl_w_data_reg[57]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[58]/q u_ctrl_w_data_reg[58]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[59]/q u_ctrl_w_data_reg[59]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[60]/q u_ctrl_w_data_reg[60]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[61]/q u_ctrl_w_data_reg[61]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[62]/q u_ctrl_w_data_reg[62]/Q -type DLAT DLAT
add mapped point u_ctrl/w_data[63]/q u_ctrl_w_data_reg[63]/Q -type DLAT DLAT
add mapped point u_ctrl/write/q u_ctrl_write_reg/Q -type DLAT DLAT
add mapped point u_ctrl/buffer_loc/q u_ctrl_buffer_loc_reg/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[0]/q u_ctrl_r_ptr_reg[0]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[1]/q u_ctrl_r_ptr_reg[1]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[2]/q u_ctrl_r_ptr_reg[2]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[3]/q u_ctrl_r_ptr_reg[3]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[4]/q u_ctrl_r_ptr_reg[4]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[5]/q u_ctrl_r_ptr_reg[5]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[6]/q u_ctrl_r_ptr_reg[6]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[7]/q u_ctrl_r_ptr_reg[7]/Q -type DFF DFF
add mapped point u_ctrl/r_ptr[8]/q u_ctrl_r_ptr_reg[8]/Q -type DFF DFF
add mapped point u_ctrl/state[0]/q u_ctrl_state_reg[0]/Q -type DFF DFF
add mapped point u_ctrl/state[1]/q u_ctrl_state_reg[1]/Q -type DFF DFF
add mapped point u_ctrl/state[2]/q u_ctrl_state_reg[2]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[0]/q u_ctrl_w_ptr_reg[0]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[1]/q u_ctrl_w_ptr_reg[1]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[2]/q u_ctrl_w_ptr_reg[2]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[3]/q u_ctrl_w_ptr_reg[3]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[4]/q u_ctrl_w_ptr_reg[4]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[5]/q u_ctrl_w_ptr_reg[5]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[6]/q u_ctrl_w_ptr_reg[6]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[7]/q u_ctrl_w_ptr_reg[7]/Q -type DFF DFF
add mapped point u_ctrl/w_ptr[8]/q u_ctrl_w_ptr_reg[8]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[0]/q u_resbuf_internal_buffer_reg[0]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[1]/q u_resbuf_internal_buffer_reg[1]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[2]/q u_resbuf_internal_buffer_reg[2]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[3]/q u_resbuf_internal_buffer_reg[3]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[4]/q u_resbuf_internal_buffer_reg[4]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[5]/q u_resbuf_internal_buffer_reg[5]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[6]/q u_resbuf_internal_buffer_reg[6]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[7]/q u_resbuf_internal_buffer_reg[7]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[8]/q u_resbuf_internal_buffer_reg[8]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[9]/q u_resbuf_internal_buffer_reg[9]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[10]/q u_resbuf_internal_buffer_reg[10]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[11]/q u_resbuf_internal_buffer_reg[11]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[12]/q u_resbuf_internal_buffer_reg[12]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[13]/q u_resbuf_internal_buffer_reg[13]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[14]/q u_resbuf_internal_buffer_reg[14]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[15]/q u_resbuf_internal_buffer_reg[15]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[16]/q u_resbuf_internal_buffer_reg[16]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[17]/q u_resbuf_internal_buffer_reg[17]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[18]/q u_resbuf_internal_buffer_reg[18]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[19]/q u_resbuf_internal_buffer_reg[19]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[20]/q u_resbuf_internal_buffer_reg[20]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[21]/q u_resbuf_internal_buffer_reg[21]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[22]/q u_resbuf_internal_buffer_reg[22]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[23]/q u_resbuf_internal_buffer_reg[23]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[24]/q u_resbuf_internal_buffer_reg[24]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[25]/q u_resbuf_internal_buffer_reg[25]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[26]/q u_resbuf_internal_buffer_reg[26]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[27]/q u_resbuf_internal_buffer_reg[27]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[28]/q u_resbuf_internal_buffer_reg[28]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[29]/q u_resbuf_internal_buffer_reg[29]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[30]/q u_resbuf_internal_buffer_reg[30]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[31]/q u_resbuf_internal_buffer_reg[31]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[32]/q u_resbuf_internal_buffer_reg[32]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[33]/q u_resbuf_internal_buffer_reg[33]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[34]/q u_resbuf_internal_buffer_reg[34]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[35]/q u_resbuf_internal_buffer_reg[35]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[36]/q u_resbuf_internal_buffer_reg[36]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[37]/q u_resbuf_internal_buffer_reg[37]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[38]/q u_resbuf_internal_buffer_reg[38]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[39]/q u_resbuf_internal_buffer_reg[39]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[40]/q u_resbuf_internal_buffer_reg[40]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[41]/q u_resbuf_internal_buffer_reg[41]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[42]/q u_resbuf_internal_buffer_reg[42]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[43]/q u_resbuf_internal_buffer_reg[43]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[44]/q u_resbuf_internal_buffer_reg[44]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[45]/q u_resbuf_internal_buffer_reg[45]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[46]/q u_resbuf_internal_buffer_reg[46]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[47]/q u_resbuf_internal_buffer_reg[47]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[48]/q u_resbuf_internal_buffer_reg[48]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[49]/q u_resbuf_internal_buffer_reg[49]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[50]/q u_resbuf_internal_buffer_reg[50]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[51]/q u_resbuf_internal_buffer_reg[51]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[52]/q u_resbuf_internal_buffer_reg[52]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[53]/q u_resbuf_internal_buffer_reg[53]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[54]/q u_resbuf_internal_buffer_reg[54]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[55]/q u_resbuf_internal_buffer_reg[55]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[56]/q u_resbuf_internal_buffer_reg[56]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[57]/q u_resbuf_internal_buffer_reg[57]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[58]/q u_resbuf_internal_buffer_reg[58]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[59]/q u_resbuf_internal_buffer_reg[59]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[60]/q u_resbuf_internal_buffer_reg[60]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[61]/q u_resbuf_internal_buffer_reg[61]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[62]/q u_resbuf_internal_buffer_reg[62]/Q -type DFF DFF
add mapped point u_resbuf/internal_buffer[63]/q u_resbuf_internal_buffer_reg[63]/Q -type DFF DFF



//Black Boxes
add mapped point sram_A sram_A -type BBOX BBOX
add mapped point sram_B sram_B -type BBOX BBOX



//Empty Modules as Blackboxes
